// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvffma205seGCBvl12fILIrA2dO2kmM9o',
    appId: '1:1082232975939:web:37c3842fb1aee8af07daf6',
    messagingSenderId: '1082232975939',
    projectId: 'tutorgroup-9c6eb',
    authDomain: 'tutorgroup-9c6eb.firebaseapp.com',
    storageBucket: 'tutorgroup-9c6eb.appspot.com',
    measurementId: 'G-MWQTK7KEME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFz94OQP6o6cTKSzwmhn69xLwmFLciITw',
    appId: '1:1082232975939:android:39d076d33e8ad39707daf6',
    messagingSenderId: '1082232975939',
    projectId: 'tutorgroup-9c6eb',
    storageBucket: 'tutorgroup-9c6eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUCyWit6sC9ivirNFSzMgcmaDjap9ADwc',
    appId: '1:1082232975939:ios:6577f4ca28a0135107daf6',
    messagingSenderId: '1082232975939',
    projectId: 'tutorgroup-9c6eb',
    storageBucket: 'tutorgroup-9c6eb.appspot.com',
    androidClientId: '1082232975939-7914shpapqhne2c8de0v7p4mscubd0j3.apps.googleusercontent.com',
    iosClientId: '1082232975939-gdtp9usdugc8n6561f8ldtpc32vs9ccp.apps.googleusercontent.com',
    iosBundleId: 'com.safin.TutorGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUCyWit6sC9ivirNFSzMgcmaDjap9ADwc',
    appId: '1:1082232975939:ios:6577f4ca28a0135107daf6',
    messagingSenderId: '1082232975939',
    projectId: 'tutorgroup-9c6eb',
    storageBucket: 'tutorgroup-9c6eb.appspot.com',
    androidClientId: '1082232975939-7914shpapqhne2c8de0v7p4mscubd0j3.apps.googleusercontent.com',
    iosClientId: '1082232975939-gdtp9usdugc8n6561f8ldtpc32vs9ccp.apps.googleusercontent.com',
    iosBundleId: 'com.safin.TutorGroup',
  );
}
